### ISSUE TITLE
ObserveQuery methods not called if Query is triggered twice

### ISSUE THREAD

**Issue by Paxol** [Jcparkyn/Phetch#4]
I encountered a particular behaviour, these are the steps to reproduce it:

1. Trigger the `Query` with args `A`, first invocation of the endpoint method
2. While the `Query` is still loading, trigger the query with args `B`, second invocation of the endpoint method
3. The `OnSuccess`/`OnFailure` methods (I haven't tested `OnChange`) are called only once for the query with args `B`

This occours also with `QueryOptions.OnSuccess`/`OnFailure` but woks fine (i.e. is colled once for each endpoint invocation) with `EndpointOptions.OnSuccess`/`OnFailure`.

I haven't tested endpoints with `CancellationToken`.

If this is the intended behaviour I suggest to specify this in the README

**Comment by Jcparkyn** [comment]
Yes, this is the intended behaviour, but it could probably use some more consideration (and you're right that the docs are lacking). From your question I assume you're using `Trigger`, which I talk about near the end of this comment.

This prompted me to look into what React Query is currently doing here, and there is some interesting [discussion](https://github.com/TanStack/query/discussions/5279) about why they recently removed onSuccess etc. from `useQuery` entirely. I think a lot of the reasoning would apply to Phetch as well, but:

- Phetch doesn't encourage sharing query logic across components like RQ does (with hooks), so a lot of the concerns about callbacks happening once for each mounted component don't apply.
- The concerns about using these callbacks for state syncing (e.g. that onSuccess doesn't fire when switching to an already cached query) are still valid. However, Blazor doesn't have a simple alternative to the `useEffect` solutions suggested in the linked discussions, so providing _some_ fallback solution is much more important here. Something like `OnDataChanged` might be the best option, but I'll wait to add that until there's a compelling use-case.
- It seems pretty clear that these callbacks are still useful for "mutations", and for these we probably want them to fire even on "ignored" calls (that have been superceded by a new arg, like your example). In particular, 
- I've been considering adding callbacks to the `Trigger` method for this purpose, but the more I think about it, the more I wonder whether it'd be cleaner for users to just `await TriggerAsync()` with a try/catch to replace the callbacks. The footgun here is that users have to make sure not to throw the exception back to Blazor.
- Some other questions are:
  - Should the callbacks still fire after the component is unmounted? I currently decided "no", but it'd be nice for users to have the option.
  - Should the behaviour be the same for `<ObserveQuery/>`, `endpoint.Use(queryOptions)`, and the normal events on the `Query` class? I think ideally yes (it is currently), but this makes the above changes more complicated.

Assuming you're using `Trigger` and you want the callbacks to fire every time, my recommendation for now would be to use `await TriggerAsync()` like described above. I'll leave this issue open until I've settled on a solution for the other problems, and I'd appreciate any input from you or others about how these things should work.

**Comment by Paxol** [comment]
I found this doing multiple deletes on a table and wanted to show a notification on success or failure, so a data mutation as you said.

I'm ok to use `await TriggerAsync()`, but I don't like the "remember to catch the exception part", think I will make an extension method of `Trigger` to pass callbacks, play a bit with it and report feedback here.
I have an important university exame in 2 weeks so this feedback may take some time to arrive.

Code of the extension method (copied your Trigger method to don't have the "not awaited task" warning):
```c#
private static async Task TriggerAsync<TArg, TResult>(this IQuery<TArg, TResult> query, TArg arg, Action<TResult> onSuccess, Action<Exception>? onFailure = null)
{
    try
    {
        var result = await query.TriggerAsync(arg);
        onSuccess.Invoke(result);
    }
    catch (Exception ex)
    {
        onFailure?.Invoke(ex);
    }
}

public static void Trigger<TArg, TResult>(this IQuery<TArg, TResult> self, TArg arg, Action<TResult> onSuccess, Action<Exception>? onFailure = null)
{
    _ = self ?? throw new ArgumentNullException(nameof(self));
    _ = self.TriggerAsync(arg, onSuccess, onFailure);
}
```
